TrackerProjectSite/TrackerProjectSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expensetracker.urls')),
    path('user_auth/', include("django.contrib.auth.urls")),
    path('user_auth/', include("user_auth.urls")),
]

TrackerProjectSite/expensetracker/urls.py
from django.urls import path
from . import views

app_name ='expensetracker'

urlpatterns = [
    path('', views.home, name='home'),
    path('view_expense_list/', views.view_list, name='view_list'),
    path('log_expense/', views.log_expense, name='log_expense'),
    path('expense_summary/', views.expense_calculations, name='expense_calculations')
]

TrackerProjectSite/user_auth/urls.py
from django.urls import path, include
from . import views

app_name = 'user_auth'

urlpatterns = [
path('', views.user_login, name='login'),
path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
path('show_user/', views.show_user, name='show_user'),
path('register_user/', views.register_user, name='register_user'),
path('logout_user/', views.logout_user, name='logout_user')
]

TrackerProjectSite/expensetracker/models.py
from django.db import models
import datetime
from datetime import datetime

# Create your models here.
#Ref source for assistance with this: https://www.youtube.com/watch?v=cWq6jQGWmEg&t=737s
EXPENSE_CATEGORY = [
    ('EDUCATION', 'Education'),
    ('ENTERTAINMENT', 'Entertainment'),
    ('PERSONAL CARE', 'Personal Care'),
    ('FOOD_&_DINING', 'Food & Dining'),
    ('CLOTHING', 'Clothing'),
    ('GIFTS_DONATIONS', 'Gifts & Donations'),
    ('UTILITIES', 'Utilities'),
    ('TRANSPORT', 'Transport'),
    ('INVESTMENTS', 'Investments'),
    ('SAVINGS', 'Savings'),
    ('TRAVEL', 'Travel'),
    ('FEES_CHARGES', 'Fees & Charges'),
    ('TAXES', 'Taxes'),
    ('HOUSING', 'Housing'),
    ('HEALTHCARE', 'Healthcare'),
    ('MISCHELLANEOUS', 'Miscellaneous')
]
    
class Expense(models.Model):
    """
    Model that represents an expense class where each field represents a database field.
    """
    date = models.DateField()
    """
    date: The date of the transaction for the expense
    """
    item_description = models.CharField(max_length=100)
    """
    str: The description of the transaction expense item
    """
    category_descr = models.CharField(max_length=50, choices=EXPENSE_CATEGORY)
    """
    str: The category description of the transaction expense item
    """

    expense_amount = models.DecimalField(decimal_places=2, max_digits=9, default=0)
    """
    decimal: The amount for the expense transaction
    """

    def __str__(self):
        return self.item_description

TrackerProjectSite/user_auth/models.py
from django.db import models

# Create your models here.

TrackerProjectSite/expensetracker/forms.py
from django.forms import ModelForm
from .models import Expense
from django import forms

# Enable a datepicker for the date field in the form.
# Ref: https://stackoverflow.com/questions/3367091/whats-the-cleanest-simplest-to-get-running-datepicker-in-django
class DateInput(forms.DateInput):
    input_type = 'date'
    format = '%d %b %Y'

# Create form where user can record their expenses
class CreateExpenseForm(ModelForm):
    class Meta:
        model = Expense
        fields = ['date', 'item_description', 'category_descr', 'expense_amount']
        widgets = {'date': DateInput()}

TrackerProjectSite/user_auth/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

# Create your models here.
class Registration_Form(UserCreationForm):
    first_name = forms.CharField(required=True)
    email = forms.EmailField(max_length=100, required=True)

    class Meta:
        model = User
        fields = ('first_name', 'email', 'username', 'password1', 'password2')

TrackerProjectSite/expensetracker/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CreateExpenseForm
from .models import Expense
from django.db.models import Sum, Count
from django.db.models.functions import TruncMonth, TruncDate
from django.contrib.auth.decorators import login_required

# Create your views here.

def home(request):
    """
    View function renders the home page

    :param request: HTTP request made using url root

    :returns: renders expensetracker/home.html as response
    """

    return render(request, 'expensetracker/home.html')

@login_required (login_url='user_auth:login')
def view_list(request):
    """
    View function renders the list of expenses

    :param request: HTTP request made using url view_expense_list/

    :returns: renders expensetracker/expense_list.html as response
    """
    Expense_list = Expense.objects.all().order_by('date')
    context = {'Expense_list': Expense_list}
    return render (request, 'expensetracker/expense_list.html', context)

@login_required (login_url='user_auth:login')
def log_expense(request):
    """
    View function enables user to input expense transaction

    :param request: HTTP request made using url log_expense/

    :returns: redirects user to url view_expense_list/ as response if input is valid

    :raises request: renders expensetracker/expense_input.html if input is invalid
    """
    expense_form = CreateExpenseForm(request.POST)
    if request.method =='POST':
        expense_form = CreateExpenseForm(request.POST)
        if expense_form.is_valid():
            expense_form.save()
            return redirect('expensetracker:view_list')
    else:
        expense_form = CreateExpenseForm()
    context = {'expense_form': expense_form}    
    return render(request, 'expensetracker/expense_input.html', context)


# Function to show the summary calculations of expenses tracked in different groups/views, including total expense, subtotals by categores
# and by month
@login_required (login_url='user_auth:login')
def expense_calculations(request):
    """
    View function renders a summary of various expense transaction information

    :param request: HTTP request made using url expense_summary/

    :returns: renders expensetracker/expense_summary.html as response
    """
    total_expense = Expense.objects.aggregate(Sum('expense_amount'))

    all_expense_objects = Expense.objects.all()
    total_expense_by_category = Expense.objects.values('category_descr').annotate(category_totals= Sum('expense_amount'), category_count_of_items_with_category= Count('category_descr'))

    total_expense_by_month = Expense.objects.annotate(month=TruncMonth('date')).values('month').annotate(month_totals= Sum('expense_amount'))

    total_expense_by_day = Expense.objects.values('date').annotate(day_totals= Sum('expense_amount'))

    context ={'total_expense': total_expense['expense_amount__sum'],
            'total_expense_by_category': total_expense_by_category,
            'all_expense_objects': all_expense_objects,
            'total_expense_by_month': total_expense_by_month,
            'total_expense_by_day': total_expense_by_day
            }
    return render(request, 'expensetracker/expense_summary.html', context)

TrackerProjectSite/user_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from .forms import Registration_Form


# Create your views here.
def user_login(request):
    return render(request, 'authentication/login.html')

def authenticate_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(reverse('user_auth:login'))
    else:
        login(request, user)
        return HttpResponseRedirect(reverse('user_auth:show_user'))
                        
def show_user(request):
    print(request.user.username)
    return render(request, 'authentication/user.html', {
        "username": request.user.username,
        "password": request.user.password
        })

def logout_user(request):
    logout(request)
    return render(request, 'authentication/logout.html')

def register_user(request):
    if request.method=='POST':
        registration_form = Registration_Form(request.POST) 
        if registration_form.is_valid():
            user = registration_form.save()
            login(request, user)
            return redirect('user_auth:show_user')
    else: 
        registration_form = Registration_Form()
    return render(request, 'authentication/user_registration.html', {'registration_form': registration_form})

TrackerProjectSite/expensetracker/templates/expensetracker/expense_input.html
<!--Page for User to Log Expenses on Tracker-->
{% extends 'expensetracker/header.html' %}

{% block title %}
Log Expense
{% endblock %}

{% block navbar %}
<div class ="row">
    <div class="col-12 pl-0 pr-0">
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #bebebe;">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/log_expense/">Record Expenses</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/view_expense_list/">Expense Detail</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/expense_summary/">Expense Overview</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/logout_user/">Logout</a>
                </li>
                 </li>       
            <ul>
        </nav>
    </div>
</div>
{% endblock %}        

{% block header %}
<div class="container">
    <div class="text-center pt-5 pb-2">
        <h1 class="display-6">Record Expense</h1>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-12 text center">
        <p class="text-center mb-4">Add your expense transaction below to log your expense:</p>

        <div class="text-center">
            <form action="{% url 'expensetracker:log_expense' %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm-12 col-md-3 col-lg-3">{{expense_form.date.label}}: {{expense_form.date }}</div>
                    <div class="col-sm-12 col-md-3 col-lg-3">{{expense_form.item_description.label}}: {{expense_form.item_description}}</div>
                    <div class="col-sm-12 col-md-3 col-lg-3">{{expense_form.category_descr.label}}: {{expense_form.category_descr}}</div>
                    <div class="col-sm-12 col-md-3 col-lg-3">{{expense_form.expense_amount.label}}: {{expense_form.expense_amount}}</div>
                </div>
                <div class="text-center mt-4">
                    <input type="submit" name="log_expense" value="Log Expense"  class="btn btn-primary">
                </div>
            </form>  
        </div>
    <div>
</div>
{% endblock %}

TrackerProjectSite/expensetracker/templates/expensetracker/expense_list.html
<!--Page Shows Full List of Detailed Trasactions to Date-->
{% extends 'expensetracker/header.html' %}

{% block title %}
Expense Transactions
{% endblock %}

{% block navbar %}
<div class ="row">
    <div class="col-12 pl-0 pr-0">
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #bebebe;">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/log_expense/">Record Expenses</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/view_expense_list/">Expense Detail</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/expense_summary/">Expense Overview</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/logout_user/">Logout</a>
                </li>
                 </li>       
            <ul>
        </nav>
    </div>
</div>
{% endblock %}  

{% block header %}
<div class="container">
    <div class="text-center pt-5 pb-2">
        <h1 class="display-6">Expense Transactions</h1>
    </div>
</div>
{% endblock %}

{% block content %}
<p class="text-center mb-4">The list of all of your historical expense transactions to date is as follows: </p>

<table class="table table-bordered table-hover table-sm">
    <thead>
        <tr>
            <th scope="col">Transaction Date</th>
            <th scope="col">Description</th>
            <th scope="col">Category</th>
            <th scope="col">Expense Amount</th>
        </tr>
    </thead>
    <tbody>
        {% for expense in Expense_list %}
        <tr>
            <td>{{expense.date|date:"d F Y"}}</td>
            <td>{{expense.item_description}}</td>
            <td>{{expense.get_category_descr_display}}</td>
            <td>R {{expense.expense_amount}}</td>
        </tr>
{% endfor %}
</tbody>
</table>

<div class="text-center mt-4 mb-4">
    <a class="btn btn-primary" href="/log_expense/" role="button">Record Expense</a>
</div>
{% endblock %}

TrackerProjectSite/expensetracker/templates/expensetracker/expense_summary.html
<!--Summary Overview of Transactions to Date Page-->
{% extends 'expensetracker/header.html' %}

{% block title %}
Expense Overview
{% endblock %}

{% block navbar %}
<div class ="row">
    <div class="col-12 pl-0 pr-0">
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #bebebe;">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/log_expense/">Record Expenses</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/view_expense_list/">Expense Detail</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/expense_summary/">Expense Overview</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/logout_user/">Logout</a>
                </li>
                 </li>       
            <ul>
        </nav>
    </div>
</div>
{% endblock %} 

{% block header %}
<div class="container">
    <div class="text-center pt-5 pb-2">
        <h1 class="display-6">Expense Overview Dashboard</h1>
    </div>
</div>
{% endblock %}

{% block content %}
<p class="text-center mb-4">The following is an overview summary of all of your expenses to date per category and across different views:</p>

<h4>Total Expenses Incurred to Date</h4><br>
<p>
Total expenses incurred to date: R{{total_expense}}
</p><br>

<h4>Total Expenses By Category</h4><br>
<!--Note: The reason for multiple for loops is to 1. Ensure that the category description is in human readable form, 2. To obtain the subtotal amounts per
category, 3. reduce the result of repeating categories due to multiple expense items in the database having the same category description-->
<table class="table table-bordered table-hover table-sm" style="table-layout: fixed;">
    <thead>
        <tr>
            <th scope="col">Category</th>
            <th scope="col">Total Expense</th>
        </tr>
    </thead>
    <tbody>
        <tr>
        <!--For loop to obtain the subtotal expense amounts for each category-->
        {% for category_totals in total_expense_by_category %}
            <!--For loop to loop through all objects in database to identify their categories (where these descriptions will be used in the final output in human readable form)-->
            {% for category in all_expense_objects %}
                <!--Loop through all objects where the category only appears once in the database (e.g. the category count total is 1) and show the human readable form in those instances -->
                {% if category.category_descr == category_totals.category_descr and category_totals.category_count_of_items_with_category == 1 %}
                    <td>{{category.get_category_descr_display}}
                    <td>R {{category_totals.category_totals}}</td>
                {% elif category_totals.category_count_of_items_with_category > 1 and category.category_descr == category_totals.category_descr %}
                    <!--Where the category appears more than once and repeats (i.e. the category count is greater than 1, only loop through the an object witht the particular category once and don't loop if already looped through the same category)-->
                    {% ifchanged %}
                        <td>{{category.get_category_descr_display}}</td>
                        <td>R {{category_totals.category_totals}}</td>
                    {% endifchanged %}
                {% endif %}
            {% endfor %}
        </tr>
        {% endfor %} 
    </tbody>
</table><br>  

<h4>Total Expenses By Month</h4><br>
<table class="table table-bordered table-hover table-sm" style="table-layout: fixed;">
    <thead>
        <tr>
            <th scope="col">Month</th>
            <th scope="col">Total Expense</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {% for month in total_expense_by_month %}
                <td>{{month.month|date:"F Y"}}</td>
                <td>R {{month.month_totals}}</td>
            </tr>
            {% endfor %}
    </tbody>
</table><br>     

<h4>Total Expenses By Day</h4><br>
<table class="table table-bordered table-hover table-sm" style="table-layout: fixed;">
    <thead>
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Total Expense</th>
        </tr>
    </thead>
    <tbody>
        {% for day in total_expense_by_day %}
        <tr>
            <td>{{day.date|date:"d F Y"}}</td>
            <td>R {{day.day_totals}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table><br>
{% endblock %}

TrackerProjectSite/expensetracker/templates/expensetracker/header.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link href ="{% static 'expensetracker/stylesheet_expensetracker.css' %}" rel ="stylesheet" type ="text/css">
</head>

<!--Insert navigation bar-->
{% block navbar %}
    <div class="col-12 pl-0 pr-0">
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #bebebe;">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/log_expense/">Record Expenses</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/view_expense_list/">Expense Detail</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/expense_summary/">Expense Overview</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/">Login</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/logout_user/">Logout</a>
                </li>
                 </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/register_user/">Sign Up</a>
                </li>         
            <ul>
        </nav>
    </div>
</div>
{% endblock %}

<header>
        {% block header %}
        {% endblock %}
</header>

<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

TrackerProjectSite/expensetracker/templates/expensetracker/home.html
<!--Home Page for App-->
{% extends 'expensetracker/header.html' %}
{% load static %}

<head>
    {% block title %}
    Expense Tracker Home
    {% endblock %}

    <link href ="{% static 'expensetracker/stylesheet_expensetracker.css' %}" rel ="stylesheet" type ="text/css">
</head>

{% block navbar %}
{% if user.is_authenticated %}
<div class ="row">
    <div class="col-12 pl-0 pr-0">
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #000000;">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/log_expense/">Record Expenses</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/view_expense_list/">Expense Detail</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/expense_summary/">Expense Overview</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/logout_user/">Logout</a>
                </li>
                </li>        
            <ul>
        </nav>
    </div>
</div>
{% else %}
<div class ="row">
    <div class="col-12 pl-0 pr-0">
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #000000;">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/">Login</a>
                </li>
                 </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/register_user/">Sign Up</a>
                </li>         
            <ul>
        </nav>
    </div>
</div>
{% endif %}
{% endblock %} 

{% block header %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 card bg-dark text-white align-items-center px-0 rounded-0">
            <img src="{% static 'expensetracker/Home_Image1.jpg' %}" class="img-fluid opacity-25" alt ="People Calculating Expenses">
                <div class="card-img-overlay text-center">
                    <h1 class="card-title p-5 mt-5 display-3">Expense Tracker App</h1>
                    <h4 class="card-text p-3 mt-5 d-flex flex-column justify-content-center">Do you struggle to keep up with your personal finances on a regular basis?</h2>
                    <p class="card-text mr-5 ml-5 pl-5 pr-5">Organise your finances and expenses with the Expense Tracker.</p>
                    <a href="#tracker-details" class="btn btn-light">Find out more</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<body>
    {% block content%}
    <div class="container-fluid px-0">
        <div class="row justify-content-center" id="tracker-details">
            <div class="col-8 mt-4 pt-4">
                <h4 class="text-center mb-4 display-5">How this this app works</h4>
                <p>You can use this expense tracker to help manage your day-to-day expenses, keep track of your total expenses
                    and view your expense overview summary by different categories and views. In particular, you can use this app to:</p>
                <ul>
                    <li>Track all your daily expenses.</li>
                    <li>View your dashboard that summarises and gives you an overview your spending activities.</li>
                </ul>
                </p>
                <p class="text-center">Log in if you're an existing user or if new, sign up to create an account to get started.</p>
                <div class="text-center pt-2 mt-2 mb-5">
                    <a href="/user_auth/" class="btn btn-dark">Get Started</a>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</body>

TrackerProjectSite/user_auth/templates/authentication/login.html
<!--App Login Page-->
{% extends 'expensetracker/header.html' %}

{% block title %}
Login
{% endblock %}

{% block navbar %}
<div class ="row">
    <div class="col-12 pl-0 pr-0">
        <nav class="navbar navbar-expand-lg navbar-light"  style="background-color: #bebebe;">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/">Login</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/register_user/">Sign Up</a>
                </li>         
            <ul>
        </nav>
    </div>
</div>
{% endblock %}        

{% block header %}
<div class="container">
    <div class="text-center pt-5 pb-2 display-5">
        <h1 class="display-6"> Login as User </h1>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="text-center">
    <form action="{% url 'user_auth:authenticate_user' %}" method="post">
        {% csrf_token %}
        <label>Username</label>
        <input type="text" name="username" placeholder="User" required>
        <br/><br/>
        <label>Password</label>
        <input type="password" name="password" required>
        <br/><br/>
        <input type="submit" value="Login" class="btn btn-dark">
    </form>
    <p class="text-center pt-3">Don't have an account? <a href="/user_auth/register_user/">Click here to register</a></p>
</div>
{% endblock %}

TrackerProjectSite/user_auth/templates/authentication/logout.html
<!--App Logout Page-->
{% extends 'expensetracker/header.html' %}

{% block title %}
Logout
{% endblock %}

{% block navbar %}
<div class ="row">
    <div class="col-12 pl-0 pr-0">
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #bebebe;">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item active">
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/">Login</a>
                </li>
                 </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/register_user/">Sign Up</a>
                </li>         
            <ul>
        </nav>
    </div>
</div>
{% endblock %}        


{% block content %}
<p class="text-center m-5 p-5"> You have successfully logged out.</p>
{% endblock %}

TrackerProjectSite/user_auth/templates/authentication/user_registration.html
<!--User Sign Up Page-->
{% extends 'expensetracker/header.html' %}

{% block title %}
Sign Up
{% endblock %}

{% block navbar %}
<div class ="row">
    <div class="col-12 pl-0 pr-0">
        <nav class="navbar navbar-expand-lg navbar-light"  style="background-color: #bebebe;">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/">Login</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/user_auth/register_user/">Sign Up</a>
                </li>         
            <ul>
        </nav>
    </div>
</div>
{% endblock %}  

{% block header %}
<div class="container">
    <div class="text-center pt-5 pb-2">
        <h1 class="display-6">Sign Up</h1>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-6">
            <form class="site-form" action="{% url 'user_auth:register_user' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{registration_form.first_name.label_tag}}
                    {{registration_form.first_name}}
                    {{registration_form.first_name.help_text}}
                </div><br>
                <div class="form-group">
                    {{registration_form.email.label_tag}}
                    {{registration_form.email}}
                    {{registration_form.email.help_text}}
                </div><br>
                <div class="form-group">
                    {{registration_form.username.label_tag}}
                    {{registration_form.username}}<br>
                    {{registration_form.username.help_text}}
                </div><br>
                <div class="form-group">
                    {{registration_form.password1.label_tag}}
                    {{registration_form.password1}}<br>
                    {{registration_form.password1.help_text}}
                </div><br>
                <div class="form-group">
                    {{registration_form.password2.label_tag}}
                    {{registration_form.password2}}<br>
                    {{registration_form.password2.help_text}}
                </div><br>
                <div class="text-center">
                    <input type="submit" value="Register" class="btn btn-dark">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}